# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/constraints/PYNQ-Z2 v1.0.xdc

# Block Designs: bd/armCPU_FPGA_design/armCPU_FPGA_design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==armCPU_FPGA_design || ORIG_REF_NAME==armCPU_FPGA_design} -quiet] -quiet

# IP: bd/armCPU_FPGA_design/ip/armCPU_FPGA_design_arm_cpu_ip_0_0/armCPU_FPGA_design_arm_cpu_ip_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==armCPU_FPGA_design_arm_cpu_ip_0_0 || ORIG_REF_NAME==armCPU_FPGA_design_arm_cpu_ip_0_0} -quiet] -quiet

# IP: bd/armCPU_FPGA_design/ip/armCPU_FPGA_design_processing_system7_0_0/armCPU_FPGA_design_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==armCPU_FPGA_design_processing_system7_0_0 || ORIG_REF_NAME==armCPU_FPGA_design_processing_system7_0_0} -quiet] -quiet

# IP: bd/armCPU_FPGA_design/ip/armCPU_FPGA_design_auto_pc_0/armCPU_FPGA_design_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==armCPU_FPGA_design_auto_pc_0 || ORIG_REF_NAME==armCPU_FPGA_design_auto_pc_0} -quiet] -quiet

# IP: bd/armCPU_FPGA_design/ip/armCPU_FPGA_design_ps7_0_axi_periph_0/armCPU_FPGA_design_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==armCPU_FPGA_design_ps7_0_axi_periph_0 || ORIG_REF_NAME==armCPU_FPGA_design_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/armCPU_FPGA_design/ip/armCPU_FPGA_design_rst_ps7_0_100M_0/armCPU_FPGA_design_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==armCPU_FPGA_design_rst_ps7_0_100M_0 || ORIG_REF_NAME==armCPU_FPGA_design_rst_ps7_0_100M_0} -quiet] -quiet

# XDC: x:/single_cycle/pynq_z2/armCPU_FPGA/armCPU_FPGA.gen/sources_1/bd/armCPU_FPGA_design/armCPU_FPGA_design_ooc.xdc
