# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: X:/single_cycle/pynq_z2/armCPU_FPGA/armCPU_FPGA.srcs/sources_1/bd/armCPU_FPGA_design/ip/armCPU_FPGA_design_processing_system7_0_0/armCPU_FPGA_design_processing_system7_0_0.xci
# IP: The module: 'armCPU_FPGA_design_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: x:/single_cycle/pynq_z2/armCPU_FPGA/armCPU_FPGA.gen/sources_1/bd/armCPU_FPGA_design/ip/armCPU_FPGA_design_processing_system7_0_0/armCPU_FPGA_design_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'armCPU_FPGA_design_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: X:/single_cycle/pynq_z2/armCPU_FPGA/armCPU_FPGA.srcs/sources_1/bd/armCPU_FPGA_design/ip/armCPU_FPGA_design_processing_system7_0_0/armCPU_FPGA_design_processing_system7_0_0.xci
# IP: The module: 'armCPU_FPGA_design_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: x:/single_cycle/pynq_z2/armCPU_FPGA/armCPU_FPGA.gen/sources_1/bd/armCPU_FPGA_design/ip/armCPU_FPGA_design_processing_system7_0_0/armCPU_FPGA_design_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'armCPU_FPGA_design_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
